# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'bassic.ui'
#
# Created: Mon Oct  8 18:11:06 2012
#      by: PyQt4 UI code generator 4.9.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui
import control, list, meaningArea, ue

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        self.control = control.control(self)
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(639, 411)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.splitter = QtGui.QSplitter(self.centralwidget)
        self.splitter.setMinimumSize(QtCore.QSize(300, 300))
        self.splitter.setLineWidth(4)
        self.splitter.setMidLineWidth(1)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName(_fromUtf8("splitter"))
        self.leftPane = QtGui.QWidget(self.splitter)
        self.leftPane.setMinimumSize(QtCore.QSize(150, 0))
        self.leftPane.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.leftPane.setObjectName(_fromUtf8("leftPane"))
        self.verticalLayout_9 = QtGui.QVBoxLayout(self.leftPane)
        self.verticalLayout_9.setMargin(0)
        self.verticalLayout_9.setObjectName(_fromUtf8("verticalLayout_9"))
        self.ModePane = QtGui.QWidget(self.leftPane)
        self.ModePane.setMinimumSize(QtCore.QSize(50, 100))
        self.ModePane.setObjectName(_fromUtf8("ModePane"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.ModePane)
        self.horizontalLayout_4.setMargin(0)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.modePaneButtons = QtGui.QWidget(self.ModePane)
        self.modePaneButtons.setObjectName(_fromUtf8("modePaneButtons"))
        self.verticalLayout_11 = QtGui.QVBoxLayout(self.modePaneButtons)
        self.verticalLayout_11.setMargin(0)
        self.verticalLayout_11.setObjectName(_fromUtf8("verticalLayout_11"))
        self.pushButtonDictionary = QtGui.QPushButton(self.modePaneButtons)
        self.pushButtonDictionary.setObjectName(_fromUtf8("pushButtonDictionary"))
        self.verticalLayout_11.addWidget(self.pushButtonDictionary)
        self.pushButtonLookUp = QtGui.QPushButton(self.modePaneButtons)
        self.pushButtonLookUp.setObjectName(_fromUtf8("pushButtonLookUp"))
        self.verticalLayout_11.addWidget(self.pushButtonLookUp)
        self.horizontalLayout_4.addWidget(self.modePaneButtons)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem)
        self.verticalLayout_9.addWidget(self.ModePane)
        self.scrollAreaLists = QtGui.QScrollArea(self.leftPane)
        self.scrollAreaLists.setFrameShape(QtGui.QFrame.StyledPanel)
        self.scrollAreaLists.setFrameShadow(QtGui.QFrame.Sunken)
        self.scrollAreaLists.setLineWidth(1)
        self.scrollAreaLists.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.scrollAreaLists.setWidgetResizable(True)
        self.scrollAreaLists.setObjectName(_fromUtf8("scrollAreaLists"))
        self.scrollAreaWidgetContents_2 = QtGui.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 205, 242))
        self.scrollAreaWidgetContents_2.setObjectName(_fromUtf8("scrollAreaWidgetContents_2"))
        self.gridLayout = QtGui.QGridLayout(self.scrollAreaWidgetContents_2)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem1, 3, 0, 1, 1)
        self.ListUENewButton = QtGui.QPushButton(self.scrollAreaWidgetContents_2)
        self.ListUENewButton.setObjectName(_fromUtf8("ListUENewButton"))
        self.gridLayout.addWidget(self.ListUENewButton, 0, 0, 1, 1)
        self.ListWordNewButton = QtGui.QPushButton(self.scrollAreaWidgetContents_2)
        self.ListWordNewButton.setObjectName(_fromUtf8("ListWordNewButton"))
        self.gridLayout.addWidget(self.ListWordNewButton, 2, 0, 1, 1)
        
        self.List = QtGui.QWidget(self.scrollAreaWidgetContents_2)
        
        #add the lists code to a list widget
        list.Ui_List().setupUi(self.List)
        
        self.List.setObjectName(_fromUtf8("List"))
        self.gridLayout.addWidget(self.List, 1, 0, 1, 1)
        self.scrollAreaLists.setWidget(self.scrollAreaWidgetContents_2)
        self.verticalLayout_9.addWidget(self.scrollAreaLists)
        self.rightPane = QtGui.QWidget(self.splitter)
        self.rightPane.setBaseSize(QtCore.QSize(0, 0))
        self.rightPane.setObjectName(_fromUtf8("rightPane"))
        self.verticalLayout_10 = QtGui.QVBoxLayout(self.rightPane)
        self.verticalLayout_10.setMargin(0)
        self.verticalLayout_10.setObjectName(_fromUtf8("verticalLayout_10"))
        self.searchArea = QtGui.QWidget(self.rightPane)
        self.searchArea.setMinimumSize(QtCore.QSize(150, 50))
        self.searchArea.setObjectName(_fromUtf8("searchArea"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.searchArea)
        self.horizontalLayout_3.setMargin(0)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.searchInput = QtGui.QLineEdit(self.searchArea)
        self.searchInput.setObjectName(_fromUtf8("searchInput"))
        self.horizontalLayout_3.addWidget(self.searchInput)
        self.searchButton = QtGui.QPushButton(self.searchArea)
        self.searchButton.setObjectName(_fromUtf8("searchButton"))
        self.horizontalLayout_3.addWidget(self.searchButton)
        self.verticalLayout_10.addWidget(self.searchArea)
        self.UEarea = QtGui.QWidget(self.rightPane)
        self.UEarea.setObjectName(_fromUtf8("UEarea"))
        ue.Ui_UEarea().setupUi(self.UEarea)
        self.verticalLayout_10.addWidget(self.UEarea)

        
        self.dictionary_2 = QtGui.QWidget(self.rightPane)
        self.dictionary_2.setObjectName(_fromUtf8("dictionary_2"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.dictionary_2)
        self.verticalLayout_2.setMargin(0)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.dictionaryWords = QtGui.QWidget(self.dictionary_2)
        self.dictionaryWords.setMinimumSize(QtCore.QSize(100, 100))
        self.dictionaryWords.setObjectName(_fromUtf8("dictionaryWords"))
        
        meaningArea.Ui_meaningArea().setupUi(self.control, self.dictionaryWords)
        
        self.verticalLayout_2.addWidget(self.dictionaryWords)
        self.DictionaryWordsScrollArea = QtGui.QScrollArea(self.dictionary_2)
        self.DictionaryWordsScrollArea.setWidgetResizable(True)
        self.DictionaryWordsScrollArea.setObjectName(_fromUtf8("DictionaryWordsScrollArea"))
        self.scrollAreaWidgetContents_3 = QtGui.QWidget()
        self.scrollAreaWidgetContents_3.setGeometry(QtCore.QRect(0, 0, 336, 307))
        self.scrollAreaWidgetContents_3.setObjectName(_fromUtf8("scrollAreaWidgetContents_3"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.scrollAreaWidgetContents_3)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.example1 = QtGui.QWidget(self.scrollAreaWidgetContents_3)
        self.example1.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.example1.setObjectName(_fromUtf8("example1"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.example1)
        self.horizontalLayout.setMargin(0)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.widget_2 = QtGui.QWidget(self.example1)
        self.widget_2.setObjectName(_fromUtf8("widget_2"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout(self.widget_2)
        self.horizontalLayout_5.setMargin(0)
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.label_2 = QtGui.QLabel(self.widget_2)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.horizontalLayout_5.addWidget(self.label_2)
        self.horizontalLayout.addWidget(self.widget_2)
        self.widget = QtGui.QWidget(self.example1)
        self.widget.setObjectName(_fromUtf8("widget"))
        self.verticalLayout = QtGui.QVBoxLayout(self.widget)
        self.verticalLayout.setMargin(0)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.example1sentence = QtGui.QLabel(self.widget)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.example1sentence.setPalette(palette)
        self.example1sentence.setAutoFillBackground(False)
        self.example1sentence.setWordWrap(True)
        self.example1sentence.setObjectName(_fromUtf8("example1sentence"))
        self.verticalLayout.addWidget(self.example1sentence)
        self.example1translation = QtGui.QLabel(self.widget)
        self.example1translation.setWordWrap(False)
        self.example1translation.setObjectName(_fromUtf8("example1translation"))
        self.verticalLayout.addWidget(self.example1translation)
        self.horizontalLayout.addWidget(self.widget)
        self.verticalLayout_5.addWidget(self.example1)
        self.line_3 = QtGui.QFrame(self.scrollAreaWidgetContents_3)
        self.line_3.setFrameShape(QtGui.QFrame.HLine)
        self.line_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_3.setObjectName(_fromUtf8("line_3"))
        self.verticalLayout_5.addWidget(self.line_3)
        self.example2 = QtGui.QWidget(self.scrollAreaWidgetContents_3)
        self.example2.setObjectName(_fromUtf8("example2"))
        self.verticalLayout_8 = QtGui.QVBoxLayout(self.example2)
        self.verticalLayout_8.setMargin(0)
        self.verticalLayout_8.setObjectName(_fromUtf8("verticalLayout_8"))
        self.example2sentence = QtGui.QLabel(self.example2)
        self.example2sentence.setObjectName(_fromUtf8("example2sentence"))
        self.verticalLayout_8.addWidget(self.example2sentence)
        self.example2translation = QtGui.QLabel(self.example2)
        self.example2translation.setObjectName(_fromUtf8("example2translation"))
        self.verticalLayout_8.addWidget(self.example2translation)
        self.verticalLayout_5.addWidget(self.example2)
        self.line_4 = QtGui.QFrame(self.scrollAreaWidgetContents_3)
        self.line_4.setFrameShape(QtGui.QFrame.HLine)
        self.line_4.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_4.setObjectName(_fromUtf8("line_4"))
        self.verticalLayout_5.addWidget(self.line_4)
        self.example3 = QtGui.QWidget(self.scrollAreaWidgetContents_3)
        self.example3.setObjectName(_fromUtf8("example3"))
        self.verticalLayout_12 = QtGui.QVBoxLayout(self.example3)
        self.verticalLayout_12.setMargin(0)
        self.verticalLayout_12.setObjectName(_fromUtf8("verticalLayout_12"))
        self.example3sentence = QtGui.QLabel(self.example3)
        self.example3sentence.setObjectName(_fromUtf8("example3sentence"))
        self.verticalLayout_12.addWidget(self.example3sentence)
        self.example3translation = QtGui.QLabel(self.example3)
        self.example3translation.setObjectName(_fromUtf8("example3translation"))
        self.verticalLayout_12.addWidget(self.example3translation)
        self.verticalLayout_5.addWidget(self.example3)
        spacerItem2 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem2)
        self.DictionaryWordsScrollArea.setWidget(self.scrollAreaWidgetContents_3)
        self.verticalLayout_2.addWidget(self.DictionaryWordsScrollArea)
        self.verticalLayout_10.addWidget(self.dictionary_2)
        self.exportArea = QtGui.QWidget(self.rightPane)
        self.exportArea.setObjectName(_fromUtf8("exportArea"))
        self.horizontalLayout_6 = QtGui.QHBoxLayout(self.exportArea)
        self.horizontalLayout_6.setMargin(0)
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem3)
        self.exportButton = QtGui.QPushButton(self.exportArea)
        self.exportButton.setObjectName(_fromUtf8("exportButton"))
        self.horizontalLayout_6.addWidget(self.exportButton)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_10.addItem(spacerItem)
        self.verticalLayout_10.addWidget(self.exportArea)
        self.horizontalLayout_2.addWidget(self.splitter)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 639, 25))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuTitle = QtGui.QMenu(self.menubar)
        self.menuTitle.setObjectName(_fromUtf8("menuTitle"))
        self.menuOptions = QtGui.QMenu(self.menubar)
        self.menuOptions.setObjectName(_fromUtf8("menuOptions"))
        self.menuAbout = QtGui.QMenu(self.menubar)
        self.menuAbout.setObjectName(_fromUtf8("menuAbout"))
        MainWindow.setMenuBar(self.menubar)
        self.actionHelp = QtGui.QAction(MainWindow)
        self.actionHelp.setObjectName(_fromUtf8("actionHelp"))
        self.actionAbout = QtGui.QAction(MainWindow)
        self.actionAbout.setObjectName(_fromUtf8("actionAbout"))
        self.actionSettings = QtGui.QAction(MainWindow)
        self.actionSettings.setObjectName(_fromUtf8("actionSettings"))
        self.actionExit = QtGui.QAction(MainWindow)
        self.actionExit.setObjectName(_fromUtf8("actionExit"))
        self.menuTitle.addAction(self.actionExit)
        self.menuOptions.addAction(self.actionSettings)
        self.menuAbout.addAction(self.actionHelp)
        self.menuAbout.addAction(self.actionAbout)
        self.menubar.addAction(self.menuTitle.menuAction())
        self.menubar.addAction(self.menuOptions.menuAction())
        self.menubar.addAction(self.menuAbout.menuAction())

        self.retranslateUi(MainWindow)
        #button connection time
        QtCore.QObject.connect(self.pushButtonDictionary, QtCore.SIGNAL(_fromUtf8("released()")), lambda: self.control.test("dictionary mode"))
        QtCore.QObject.connect(self.pushButtonLookUp, QtCore.SIGNAL(_fromUtf8("released()")), lambda: self.control.test("lookup mode"))

        QtCore.QObject.connect(self.pushButtonDictionary, QtCore.SIGNAL(_fromUtf8("released()")), lambda: self.control.dictionaryMode(self.searchInput.text()))
        QtCore.QObject.connect(self.pushButtonLookUp, QtCore.SIGNAL(_fromUtf8("released()")), lambda: self.control.lookUpMode(self.searchInput.text()))

        QtCore.QObject.connect(self.ListUENewButton, QtCore.SIGNAL(_fromUtf8("released()")), lambda: self.control.test("new ue list button"))
        QtCore.QObject.connect(self.ListWordNewButton, QtCore.SIGNAL(_fromUtf8("released()")), lambda: self.control.test("new word list button"))
        
        QtCore.QObject.connect(self.searchButton, QtCore.SIGNAL(_fromUtf8("released()")), lambda: self.control.test("search button"))
        QtCore.QObject.connect(self.searchButton, QtCore.SIGNAL(_fromUtf8("released()")), lambda: self.control.search(self.searchInput.text()))
        QtCore.QObject.connect(self.searchInput, QtCore.SIGNAL(_fromUtf8("returnPressed()")), lambda: self.control.search(self.searchInput.text()))
        QtCore.QObject.connect(self.exportButton, QtCore.SIGNAL(_fromUtf8("released()")), lambda: self.control.test("export button"))

        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        self.control.lookUpMode("")

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "MainWindow", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonDictionary.setText(QtGui.QApplication.translate("MainWindow", "Dictionary", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonLookUp.setText(QtGui.QApplication.translate("MainWindow", "Look up", None, QtGui.QApplication.UnicodeUTF8))
        self.ListUENewButton.setText(QtGui.QApplication.translate("MainWindow", "New UE List", None, QtGui.QApplication.UnicodeUTF8))
        self.ListWordNewButton.setText(QtGui.QApplication.translate("MainWindow", "New Word List", None, QtGui.QApplication.UnicodeUTF8))
        self.searchButton.setText(QtGui.QApplication.translate("MainWindow", "Search", None, QtGui.QApplication.UnicodeUTF8))
        self.dictionary_2.setProperty("mode_type", QtGui.QApplication.translate("MainWindow", "TEXT", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("MainWindow", "9.99", None, QtGui.QApplication.UnicodeUTF8))
        self.example1sentence.setText(QtGui.QApplication.translate("MainWindow", "先生は青のペンを持っています。", None, QtGui.QApplication.UnicodeUTF8))
        self.example1translation.setText(QtGui.QApplication.translate("MainWindow", "The teacher has a blue pen.", None, QtGui.QApplication.UnicodeUTF8))
        self.example2sentence.setText(QtGui.QApplication.translate("MainWindow", "先生は青のペンを持っています。", None, QtGui.QApplication.UnicodeUTF8))
        self.example2translation.setText(QtGui.QApplication.translate("MainWindow", "The teacher has a blue pen.", None, QtGui.QApplication.UnicodeUTF8))
        self.example3sentence.setText(QtGui.QApplication.translate("MainWindow", "先生は青のペンを持っています。", None, QtGui.QApplication.UnicodeUTF8))
        self.example3translation.setText(QtGui.QApplication.translate("MainWindow", "The teacher has a blue pen.", None, QtGui.QApplication.UnicodeUTF8))
        self.exportButton.setText(QtGui.QApplication.translate("MainWindow", "Export", None, QtGui.QApplication.UnicodeUTF8))
        self.menuTitle.setTitle(QtGui.QApplication.translate("MainWindow", "title", None, QtGui.QApplication.UnicodeUTF8))
        self.menuOptions.setTitle(QtGui.QApplication.translate("MainWindow", "options", None, QtGui.QApplication.UnicodeUTF8))
        self.menuAbout.setTitle(QtGui.QApplication.translate("MainWindow", "about", None, QtGui.QApplication.UnicodeUTF8))
        self.actionHelp.setText(QtGui.QApplication.translate("MainWindow", "help", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAbout.setText(QtGui.QApplication.translate("MainWindow", "about", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSettings.setText(QtGui.QApplication.translate("MainWindow", "settings", None, QtGui.QApplication.UnicodeUTF8))
        self.actionExit.setText(QtGui.QApplication.translate("MainWindow", "exit", None, QtGui.QApplication.UnicodeUTF8))
        self.actionExit.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+Q", None, QtGui.QApplication.UnicodeUTF8))


def new():
    import sys
    app = QtGui.QApplication(sys.argv)
    MainWindow = QtGui.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

if __name__ == "__main__":
    new()
    